"""Synthetic asset inventory for the fictional Northstar Financial Services
environment (see docs/decisions/0005-synthetic-environment.md). Every
field is representative of a real enterprise environment's shape, not
copied from any real company.

Dependency chain models the Section 8 example directly:
Internet -> Web Portal -> API Gateway -> Payment Service -> Customer Database
"""

NORTHSTAR_ASSETS = [
    {
        "asset_tag": "AST-001",
        "name": "Customer Web Portal",
        "asset_type": "application",
        "owner": "Digital Channels Team",
        "business_unit": "Retail Banking",
        "environment": "production",
        "criticality": "high",
        "data_classification": "confidential",
        "internet_exposed": True,
        "technology": "React SPA + Node.js BFF",
        "authentication_method": "OIDC (customer IdP)",
        "encrypted": True,
        "logging_enabled": True,
        "backup_enabled": False,
        "notes": "Primary customer-facing online banking portal.",
    },
    {
        "asset_tag": "AST-002",
        "name": "Public API Gateway",
        "asset_type": "api",
        "owner": "Platform Engineering",
        "business_unit": "Technology",
        "environment": "production",
        "criticality": "critical",
        "data_classification": "confidential",
        "internet_exposed": True,
        "technology": "Kong API Gateway",
        "authentication_method": "OAuth2 client credentials + JWT",
        "encrypted": True,
        "logging_enabled": True,
        "backup_enabled": False,
        "notes": "Entry point for all customer-facing and partner API traffic.",
    },
    {
        "asset_tag": "AST-003",
        "name": "Payment Processing Service",
        "asset_type": "application",
        "owner": "Payments Engineering",
        "business_unit": "Retail Banking",
        "environment": "production",
        "criticality": "critical",
        "data_classification": "restricted",
        "internet_exposed": False,
        "technology": "Java Spring Boot",
        "authentication_method": "mTLS (internal service mesh)",
        "encrypted": True,
        "logging_enabled": True,
        "backup_enabled": True,
        "notes": "Processes card and ACH payment transactions.",
    },
    {
        "asset_tag": "AST-004",
        "name": "Customer Database",
        "asset_type": "database",
        "owner": "Data Platform Team",
        "business_unit": "Technology",
        "environment": "production",
        "criticality": "critical",
        "data_classification": "restricted",
        "internet_exposed": False,
        "technology": "PostgreSQL 15 (managed)",
        "authentication_method": "IAM database authentication",
        "encrypted": True,
        "logging_enabled": True,
        "backup_enabled": True,
        "notes": "Stores customer PII, account, and transaction history.",
    },
    {
        "asset_tag": "AST-005",
        "name": "Employee Identity Provider",
        "asset_type": "identity",
        "owner": "IT Security",
        "business_unit": "Technology",
        "environment": "production",
        "criticality": "critical",
        "data_classification": "confidential",
        "internet_exposed": True,
        "technology": "Okta",
        "authentication_method": "SSO + MFA",
        "encrypted": True,
        "logging_enabled": True,
        "backup_enabled": False,
        "notes": "Central identity provider for all employee access to internal systems.",
    },
    {
        "asset_tag": "AST-006",
        "name": "Customer Document Storage",
        "asset_type": "cloud_resource",
        "owner": "Platform Engineering",
        "business_unit": "Technology",
        "environment": "production",
        "criticality": "high",
        "data_classification": "confidential",
        "internet_exposed": False,
        "technology": "AWS S3",
        "authentication_method": "IAM role-based",
        "encrypted": True,
        "logging_enabled": False,
        "backup_enabled": True,
        "notes": (
            "Stores scanned KYC documents and statements. Access logging not yet enabled - "
            "see Cloud Security findings."
        ),
    },
    {
        "asset_tag": "AST-007",
        "name": "Internal HR Application",
        "asset_type": "application",
        "owner": "HR Systems Team",
        "business_unit": "Human Resources",
        "environment": "production",
        "criticality": "medium",
        "data_classification": "confidential",
        "internet_exposed": False,
        "technology": "Workday (hosted)",
        "authentication_method": "SSO",
        "encrypted": True,
        "logging_enabled": True,
        "backup_enabled": True,
        "notes": "Employee records, payroll, and benefits administration.",
    },
    {
        "asset_tag": "AST-008",
        "name": "Salesforce CRM",
        "asset_type": "saas",
        "owner": "Sales Operations",
        "business_unit": "Commercial Banking",
        "environment": "production",
        "criticality": "high",
        "data_classification": "confidential",
        "internet_exposed": True,
        "technology": "Salesforce (SaaS)",
        "authentication_method": "SSO",
        "encrypted": True,
        "logging_enabled": True,
        "backup_enabled": False,
        "notes": (
            "Customer relationship management for commercial banking clients. "
            "See Vendor Risk (Phase 9)."
        ),
    },
    {
        "asset_tag": "AST-009",
        "name": "AI Customer Support Assistant",
        "asset_type": "ai_system",
        "owner": "Customer Experience Team",
        "business_unit": "Retail Banking",
        "environment": "production",
        "criticality": "medium",
        "data_classification": "confidential",
        "internet_exposed": True,
        "technology": "Third-party LLM API + internal orchestration",
        "authentication_method": "Customer session token",
        "encrypted": True,
        "logging_enabled": True,
        "backup_enabled": False,
        "notes": "Drafts and sends responses to customer support chat inquiries. See AI Security (Phase 10).",
    },
    {
        "asset_tag": "AST-010",
        "name": "Internal RAG Knowledge Assistant",
        "asset_type": "ai_system",
        "owner": "Enterprise Architecture",
        "business_unit": "Technology",
        "environment": "production",
        "criticality": "medium",
        "data_classification": "internal",
        "internet_exposed": False,
        "technology": "RAG pipeline over internal policy/knowledge documents",
        "authentication_method": "Employee SSO",
        "encrypted": True,
        "logging_enabled": True,
        "backup_enabled": False,
        "notes": "Answers employee questions against internal policy documents. See RAG Security (Phase 11).",
    },
    {
        "asset_tag": "AST-011",
        "name": "Corporate Endpoint Fleet",
        "asset_type": "endpoint",
        "owner": "IT Operations",
        "business_unit": "Technology",
        "environment": "production",
        "criticality": "medium",
        "data_classification": "internal",
        "internet_exposed": False,
        "technology": "Windows 11 / macOS, managed via MDM",
        "authentication_method": "SSO + MFA",
        "encrypted": True,
        "logging_enabled": True,
        "backup_enabled": False,
        "notes": "~500 employee laptops/desktops.",
    },
    {
        "asset_tag": "AST-012",
        "name": "Core Banking Server",
        "asset_type": "server",
        "owner": "Core Banking Team",
        "business_unit": "Retail Banking",
        "environment": "production",
        "criticality": "critical",
        "data_classification": "restricted",
        "internet_exposed": False,
        "technology": "On-prem mainframe-adjacent core banking platform",
        "authentication_method": "Service account + certificate",
        "encrypted": True,
        "logging_enabled": True,
        "backup_enabled": True,
        "notes": "System of record for account balances and ledger entries.",
    },
    {
        "asset_tag": "AST-013",
        "name": "Edge Load Balancer",
        "asset_type": "network_device",
        "owner": "Network Engineering",
        "business_unit": "Technology",
        "environment": "production",
        "criticality": "high",
        "data_classification": "internal",
        "internet_exposed": True,
        "technology": "F5 BIG-IP",
        "authentication_method": "Admin certificate",
        "encrypted": True,
        "logging_enabled": True,
        "backup_enabled": False,
        "notes": "Terminates public TLS traffic in front of the API Gateway.",
    },
    {
        "asset_tag": "AST-014",
        "name": "Legacy QA Test Server",
        "asset_type": "server",
        "owner": "QA Team",
        "business_unit": "Technology",
        "environment": "test",
        "criticality": "low",
        "data_classification": "internal",
        "internet_exposed": False,
        "technology": "Ubuntu 18.04 (end of life)",
        "authentication_method": "Local accounts",
        "encrypted": False,
        "logging_enabled": False,
        "backup_enabled": False,
        "notes": (
            "Isolated network segment, synthetic test data only, scheduled for decommission. "
            "Deliberately included to illustrate CVSS-vs-business-risk (Section 9): a high-CVSS "
            "finding here carries far less business risk than a moderate one on AST-002."
        ),
    },
    {
        "asset_tag": "AST-015",
        "name": "Application Container Platform",
        "asset_type": "container",
        "owner": "Platform Engineering",
        "business_unit": "Technology",
        "environment": "production",
        "criticality": "high",
        "data_classification": "confidential",
        "internet_exposed": False,
        "technology": "Kubernetes (EKS)",
        "authentication_method": "IAM role-based (IRSA)",
        "encrypted": True,
        "logging_enabled": True,
        "backup_enabled": False,
        "notes": "Hosts the Payment Processing Service and internal applications.",
    },
]

# (from_asset_tag, to_asset_tag, description)
NORTHSTAR_ASSET_DEPENDENCIES = [
    ("AST-001", "AST-002", "Web portal calls the public API gateway for all account operations"),
    ("AST-002", "AST-003", "Gateway routes payment initiation requests to the payment service"),
    ("AST-003", "AST-004", "Payment service reads/writes customer and account records"),
    ("AST-003", "AST-015", "Payment service runs as a workload on the container platform"),
    ("AST-002", "AST-013", "Gateway sits behind the edge load balancer"),
    ("AST-009", "AST-004", "Support assistant looks up customer account context"),
    ("AST-010", "AST-006", "Knowledge assistant indexes documents from customer document storage"),
]
